@startuml
'https://plantuml.com/class-diagram

entity Candidato {
    <<PK>> id INTEGER
    ---
    nombre VARCHAR
    apellido VARCHAR
}

entity Empresa {
    <<PK>> id INTEGER
    nombre VARCHAR
}

entity Postulacion {
    <<PK>> id INTEGER
    ---
    <<FK>> evaluacion_id INTEGER
    <<FK>> candidato_id INTEGER
}

entity Evaluacion {
    <<PK>> id INTEGER
    ---
    nombre VARCHAR
}

entity Pregunta {
    <<PK>> id INTEGER
    ---
    <<FK>> evaluacion_id INTEGER
    consigna VARCHAR
    tipo VARCHAR
}

entity Habilidad_Pregunta {
    <<PK, FK>> pregunta_id INTEGER
    <<PK, FK>> habilidad_id INTEGER
}

entity Habilidad {
    <<PK>> id INTEGER
    ---
    nombre VARCHAR
}

entity RespuestaCorrecta {
    <<PK>> id INTEGER
    ---
    <<FK>> pregunta_id INTEGER
    detalle VARCHAR
}

entity Indice {
    <<PK>> id INTEGER
    ---
    nombre VARCHAR
}

entity Metrica {
    <<PK>> id INTEGER
    ---
    nombre VARCHAR
}

entity Indice_Metrica {
    <<PK, FK>> indice_id INTEGER
    <<PK, FK>> metrica_id INTEGER
}

entity Evaluacion_Indice {
    <<PK, FK>> indice_id INTEGER
    <<PK, FK>> evaluacion_id INTEGER
}

entity RespuestaEvaluacion {
    <<PK>> id INTEGER
    ---
    respuesta VARCHAR
    puntaje INTEGER
}

entity IndiceRespuesta {
    <<PK>> id INTEGER
    ---
    <<FK>> indice_id INTEGER
    resultado FLOAT
}

entity CampaniaReclutamiento {
    <<PK>> id INTEGER
    ---
    <<FK>> empresa_id INTEGER
    evaluacionDeReferencia_id INTEGER
}

entity PostulacionRecomendada {
    <<PK, FK>> campania_id INTEGER
    <<PK, FK>> postulacion_id INTEGER
}

CampaniaReclutamiento }o-=|| Empresa
CampaniaReclutamiento }o--|| Evaluacion
CampaniaReclutamiento ||-o{ PostulacionRecomendada
Postulacion ||-o{ PostulacionRecomendada
Postulacion }o--|| Evaluacion
Postulacion }o--|| Candidato
Postulacion ||--|{ RespuestaEvaluacion
RespuestaEvaluacion ||--o{ IndiceRespuesta
IndiceRespuesta }o--|| Indice
Indice ||-o{ Indice_Metrica
Metrica ||--o{ Indice_Metrica
Evaluacion ||--o{ Pregunta
Evaluacion ||--|{ Evaluacion_Indice
Indice ||--o{ Evaluacion_Indice
Pregunta ||--|{ Habilidad_Pregunta
Pregunta ||--o{ RespuestaCorrecta
Habilidad ||--o{ Habilidad_Pregunta

@enduml